version: '3.7'
services:
  server:
    image: "server:latest"
    networks:
      - idp_network
    deploy:
      replicas: 2
      endpoint_mode: dnsrr
  client:
      image: "client:latest"
      networks:
        - idp_network
      ports:
        - target: 8081
          published: 8081
          protocol: tcp
          mode: host
      deploy:
        mode: global

networks:
  idp_network:
    external: true