server:
  port: 8090
  servlet:
    context-path: /damai-server
spring:
  grpc:
    enable: true
    port: 6565
  datasource:
    name: datasource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/damai?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      #配置初始化大小/最大/最小
      initial-size: 5
      min-idle: 10
      max-active: 30
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小的生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache 并指定每一个连接上的PSCache的大小。oracle设置为true mysql设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  servlet:
    multipart:
      max-file-size: 1024000000
      max-request-size: 1024000000
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: cn.ecnu.damai.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 获取自增主键的值
    use-generated-keys: true
    lazy-loading-enabled: true
logging:
  level:
    cn.kyrie: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql